# Site settings
title: CHEMENG 444 / ENERGY 256 Winter 2016
subtitle: Electronic Structure Theory and Applications to Chemical Kinetics
url: "http://chemeng444.github.io"
baseurl: ""

# Build settings
permalink: pretty